### PR TITLE
Feature employee

### PR DESCRIPTION
**Pull request by hawariotm**
fetched data from json file and rendered in a view. completed functionality of employee view.
@nishintn

### CODE REVIEW

**Comment by mad-nishin** [comment]
@hawariotm ,
I would like to see the app. Please share the hosted url as well. Will merge the PR then.

**Comment by hawariotm** [comment]
added to gh-pages
http://aneesps.github.io/Space-Demo/views/employeeview.html

**Comment by hawariotm** [comment]
please merge my previous commits.
i have new commits
@nishintn

**Comment by hawariotm** [comment]
i already hosted it in gh-pages  and shared with you through the chat.
http://aneesps.github.io/Space-Demo/views/employeeview.html

**Pull request merged**
